# Generated by Django 5.2.5 on 2025-08-18 11:01

import apps.datamas.models
import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Daerah",
            fields=[
                ("id_daerah", models.AutoField(primary_key=True, serialize=False)),
                ("nama_daerah", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Desa",
            fields=[
                ("id_desa", models.AutoField(primary_key=True, serialize=False)),
                ("nama_desa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Kelompok",
            fields=[
                ("id_kel", models.AutoField(primary_key=True, serialize=False)),
                ("nama_kel", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DataMas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Admin"),
                            ("admin", "Admin"),
                            ("user", "User"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("full_nama", models.CharField(blank=True, max_length=255, null=True)),
                ("gender", models.CharField(blank=True, max_length=255, null=True)),
                ("no_hp", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.datamas.models.avatar_with_id,
                    ),
                ),
                (
                    "keterangan",
                    django_quill.fields.QuillField(
                        default='{"delta": "", "html": "Keterangan atau catatan dari data"}'
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataKependudukan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nik",
                    models.CharField(max_length=16, unique=True, verbose_name="NIK"),
                ),
                (
                    "nama_lengkap",
                    models.CharField(max_length=255, verbose_name="Nama Lengkap"),
                ),
                (
                    "jenis_kelamin",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")],
                        max_length=1,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                (
                    "tempat_lahir",
                    models.CharField(max_length=100, verbose_name="Tempat Lahir"),
                ),
                ("tanggal_lahir", models.DateField(verbose_name="Tanggal Lahir")),
                ("alamat_lengkap", models.TextField(verbose_name="Alamat Lengkap")),
                ("rt", models.CharField(max_length=3, verbose_name="RT")),
                ("rw", models.CharField(max_length=3, verbose_name="RW")),
                (
                    "agama",
                    models.CharField(
                        choices=[
                            ("islam", "Islam"),
                            ("kristen", "Kristen"),
                            ("katolik", "Katolik"),
                            ("hindu", "Hindu"),
                            ("buddha", "Buddha"),
                            ("khonghucu", "Khonghucu"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Agama",
                    ),
                ),
                (
                    "status_perkawinan",
                    models.CharField(
                        choices=[
                            ("belum_kawin", "Belum Kawin"),
                            ("kawin", "Kawin"),
                            ("cerai_hidup", "Cerai Hidup"),
                            ("cerai_mati", "Cerai Mati"),
                        ],
                        max_length=20,
                        verbose_name="Status Perkawinan",
                    ),
                ),
                (
                    "pekerjaan",
                    models.CharField(
                        choices=[
                            ("belum_bekerja", "Belum/Tidak Bekerja"),
                            ("mengurus_rumah_tangga", "Mengurus Rumah Tangga"),
                            ("pelajar", "Pelajar/Mahasiswa"),
                            ("pensiunan", "Pensiunan"),
                            ("pegawai_negeri", "Pegawai Negeri Sipil"),
                            ("tni", "TNI"),
                            ("kepolisian", "KEPOLISIAN"),
                            ("perdagangan", "Perdagangan"),
                            ("petani", "Petani/Pekebun"),
                            ("peternak", "Peternak"),
                            ("nelayan", "Nelayan/Perikanan"),
                            ("industri", "Industri"),
                            ("konstruksi", "Konstruksi"),
                            ("transportasi", "Transportasi"),
                            ("karyawan_swasta", "Karyawan Swasta"),
                            ("karyawan_bumn", "Karyawan BUMN"),
                            ("karyawan_bumd", "Karyawan BUMD"),
                            ("karyawan_honorer", "Karyawan Honorer"),
                            ("buruh_harian_lepas", "Buruh Harian Lepas"),
                            ("buruh_tani", "Buruh Tani/Perkebunan"),
                            ("buruh_nelayan", "Buruh Nelayan/Perikanan"),
                            ("buruh_peternakan", "Buruh Peternakan"),
                            ("pembantu_rumah_tangga", "Pembantu Rumah Tangga"),
                            ("tukang_cukur", "Tukang Cukur"),
                            ("tukang_listrik", "Tukang Listrik"),
                            ("tukang_batu", "Tukang Batu"),
                            ("tukang_kayu", "Tukang Kayu"),
                            ("tukang_sol_sepatu", "Tukang Sol Sepatu"),
                            ("tukang_las", "Tukang Las/Pandai Besi"),
                            ("tukang_jahit", "Tukang Jahit"),
                            ("tukang_gigi", "Tukang Gigi"),
                            ("penata_rias", "Penata Rias"),
                            ("penata_busana", "Penata Busana"),
                            ("penata_rambut", "Penata Rambut"),
                            ("mekanik", "Mekanik"),
                            ("seniman", "Seniman"),
                            ("tabib", "Tabib"),
                            ("paraji", "Paraji"),
                            ("perancang_busana", "Perancang Busana"),
                            ("penterjemah", "Penterjemah"),
                            ("imam_masjid", "Imam Masjid"),
                            ("pendeta", "Pendeta"),
                            ("pastor", "Pastor"),
                            ("wartawan", "Wartawan"),
                            ("ustadz", "Ustadz/Mubaligh"),
                            ("juru_masak", "Juru Masak"),
                            ("promotor_acara", "Promotor Acara"),
                            ("anggota_dpr_ri", "Anggota DPR-RI"),
                            ("anggota_dpd", "Anggota DPD"),
                            ("anggota_bpk", "Anggota BPK"),
                            ("presiden", "Presiden"),
                            ("wakil_presiden", "Wakil Presiden"),
                            (
                                "anggota_mahkamah_konstitusi",
                                "Anggota Mahkamah Konstitusi",
                            ),
                            ("anggota_kabinet", "Anggota Kabinet Kementerian"),
                            ("duta_besar", "Duta Besar"),
                            ("gubernur", "Gubernur"),
                            ("wakil_gubernur", "Wakil Gubernur"),
                            ("bupati", "Bupati"),
                            ("wakil_bupati", "Wakil Bupati"),
                            ("walikota", "Walikota"),
                            ("wakil_walikota", "Wakil Walikota"),
                            ("anggota_dprd_provinsi", "Anggota DPRD Provinsi"),
                            ("anggota_dprd_kabupaten", "Anggota DPRD Kabupaten/Kota"),
                            ("dosen", "Dosen"),
                            ("guru", "Guru"),
                            ("pilot", "Pilot"),
                            ("pengacara", "Pengacara"),
                            ("notaris", "Notaris"),
                            ("arsitek", "Arsitek"),
                            ("akuntan", "Akuntan"),
                            ("konsultan", "Konsultan"),
                            ("dokter", "Dokter"),
                            ("bidan", "Bidan"),
                            ("perawat", "Perawat"),
                            ("apoteker", "Apoteker"),
                            ("psikiater", "Psikiater/Psikolog"),
                            ("penyiar_televisi", "Penyiar Televisi"),
                            ("penyiar_radio", "Penyiar Radio"),
                            ("pelaut", "Pelaut"),
                            ("peneliti", "Peneliti"),
                            ("sopir", "Sopir"),
                            ("pialang", "Pialang"),
                            ("paranormal", "Paranormal"),
                            ("pedagang", "Pedagang"),
                            ("perangkat_desa", "Perangkat Desa"),
                            ("kepala_desa", "Kepala Desa"),
                            ("biarawati", "Biarawati"),
                            ("wiraswasta", "Wiraswasta"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=50,
                        verbose_name="Pekerjaan",
                    ),
                ),
                (
                    "pendidikan_terakhir",
                    models.CharField(
                        choices=[
                            ("tidak_sekolah", "Tidak/Belum Sekolah"),
                            ("tidak_tamat_sd", "Tidak Tamat SD/Sederajat"),
                            ("tamat_sd", "Tamat SD/Sederajat"),
                            ("tamat_smp", "SLTP/Sederajat"),
                            ("tamat_sma", "SLTA/Sederajat"),
                            ("diploma_i", "Diploma I/II"),
                            ("akademi", "Akademi/Diploma III/S.Muda"),
                            ("diploma_iv", "Diploma IV/Strata I"),
                            ("strata_ii", "Strata II"),
                            ("strata_iii", "Strata III"),
                        ],
                        max_length=30,
                        verbose_name="Pendidikan Terakhir",
                    ),
                ),
                (
                    "nama_ayah",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nama Ayah"
                    ),
                ),
                (
                    "nama_ibu",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nama Ibu"
                    ),
                ),
                (
                    "nama_pasangan",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nama Pasangan",
                    ),
                ),
                (
                    "no_telepon",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="No. Telepon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "keterangan",
                    models.TextField(blank=True, null=True, verbose_name="Keterangan"),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="kependudukan/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat Pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diupdate Pada"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                (
                    "daerah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamas.daerah",
                        verbose_name="Daerah",
                    ),
                ),
                (
                    "desa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamas.desa",
                        verbose_name="Desa",
                    ),
                ),
                (
                    "kelompok",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datamas.kelompok",
                        verbose_name="Kelompok",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Kependudukan",
                "verbose_name_plural": "Data Kependudukan",
                "ordering": ["nama_lengkap"],
            },
        ),
    ]
