# Generated by Django 4.2.9 on 2025-10-30 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datamas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="desa",
            name="id_daerah",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="desa_set",
                to="datamas.daerah",
            ),
        ),
        migrations.AddField(
            model_name="kelompok",
            name="id_desa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kelompok_set",
                to="datamas.desa",
            ),
        ),
    ]
