# Generated by Django 4.2.9 on 2025-10-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datamas", "0002_desa_id_daerah_kelompok_id_desa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datakependudukan",
            name="nik",
            field=models.CharField(max_length=16, unique=True, verbose_name="ID_data"),
        ),
    ]
